#!/bin/bash                                                                        
echo "Content-type: text/html"
echo ""
make
echo "<html><title>State Street Restaurants</title>"
echo "<style>"
echo " body {"
echo "     text-align:center;"
echo "     background-color: Gainsboro"
echo " }"
echo " table {"
echo "     margin-left:auto;"
echo "     margin-right:auto;"
echo "     background-color: BurlyWood;"
echo
echo " }"
echo " button {"
echo "     background-color: BlanchedAlmond;"
echo "     border: 1px solid black;"
echo "     font-size: 16px;"
echo " }"
echo " tr, td {"
echo "     border: 1px solid black;"
echo "     background-color: BlanchedAlmond;"
echo " }"
echo " td:hover {background-color: BurlyWood;}"
echo " button:hover {background-color: BurlyWood;}"
echo "</style>"
echo "<script>"
echo " function handleButtonClick2() {"
echo "   let inputs = document.querySelectorAll(\"input\");"
echo "   location.replace(\"http://35.226.220.167/cgi-bin/project-four-af/brendel2_Front_End_Developer_1/FrontEnd.cgi?\" + inputs[0].value);"
echo " }"
echo " function handleButtonClick1() {"
echo "   let r = Math.floor(Math.random() * Math.floor(41) + 1);"
echo "   location.replace(\"http://35.226.220.167/cgi-bin/project-four-af/brendel2_Front_End_Developer_1/FrontEnd.cgi?\" + r);"
echo " } "
echo "</script>"
echo "<body>"
echo "<h1>State Street Restaurants</h1>"
java Connector $QUERY_STRING
echo "<h2>Search For Restaurant</h2>"
echo "<p>Using the restaurant's address, find out more about it</p>"
echo "<input type=\"text\">"
echo "<button onclick=\"handleButtonClick2();\">search</button><br/>"
echo "<h2>Random Restaurant</h2>"
echo "<p>Display information on a random restaurant</p>"
echo "<button onclick=\"handleButtonClick1();\">Random Restaurant</button><br/>"
echo "<h3>Supported Restaurants</h3>"
echo "<p>Here is a list of all of the searchable restaurants:</p>"
java RestaurantList
echo "</body>"
echo "</html>"
